package TryCatch;

import java.io.IOException;

public class MainClass {

	public static void main(String[] args) throws ArrayIndexOutOfBoundsException, IOException {
		Test3 tt = new Test3();
		tt.show1();
		tt.show2(); 

	}

}
